export const CardsDB = [
    {
        id: 'ra_switch_hitter',
        name: 'Switch Hitter',
        positiveEffect:
            'Shooting your secondary weapon fills up your primary ammo.',
        negativeEffect:
            'Shooting your primary weapon consumes both primary and secondary ammo.',
        rarity: 'uncommon',
        category: 'challenge',
        type: 'raid',
        texture: 'cc_raid_uncommon_switch_hitter_hud',
        bonusXpMultiplier: 1.65,
    },
    {
        id: 'ra_gunslingers',
        name: 'Gunslingers',
        positiveEffect: 'Pistol damage increased by 15%',
        negativeEffect: 'No primary weapon. (ammo capacity lowered by 100%)',
        rarity: 'uncommon',
        category: 'challenge',
        type: 'raid',
        texture: 'cc_raid_uncommon_gunslingers_hud',
        bonusXpMultiplier: 1.65,
    },
    {
        id: 'ra_fresh_troops',
        name: 'Fresh Troops',
        positiveEffect: 'Loot drop chance increased by 25%',
        negativeEffect: 'Enemies have 50% more Health',
        rarity: 'uncommon',
        category: 'challenge',
        type: 'raid',
        texture: 'cc_raid_uncommon_fresh_troops_hud',
        bonusXpMultiplier: 2.25,
    },
    {
        id: 'ra_dont_you_die_on_me',
        name: "Don't You Die On Me!",
        positiveEffect: 'Bleedout timer increased by 10 seconds.',
        negativeEffect: 'None of the players can ever die during the raid.',
        rarity: 'uncommon',
        category: 'challenge',
        type: 'raid',
        texture: 'cc_raid_uncommon_dont_you_die_on_me_hud',
        bonusXpMultiplier: 1.8,
    },
    {
        id: 'ra_no_second_chances',
        name: 'No Second Chances',
        positiveEffect: 'Player Health is increased by 10',
        negativeEffect:
            'None of the players can ever go to bleedout during the raid.',
        rarity: 'rare',
        category: 'challenge',
        type: 'raid',
        texture: 'cc_raid_rare_no_second_chances_hud',
        bonusXpMultiplier: 2.2,
    },
    {
        id: 'ra_a_perfect_score',
        name: 'A Perfect Score',
        positiveEffect: 'All chests are locked with greater rewards.',
        negativeEffect:
            'Challenge card rewards are nullified when failing a minigame.',
        rarity: 'rare',
        category: 'challenge',
        type: 'raid',
        texture: 'cc_raid_rare_a_perfect_score_hud',
        bonusXpMultiplier: 2.2,
    },
    {
        id: 'ra_helmet_shortage',
        name: 'Helmet Shortage',
        positiveEffect: 'Headshots deal 300% more damage.',
        negativeEffect: 'Player Health is reduced by 50%',
        rarity: 'rare',
        category: 'challenge',
        type: 'raid',
        texture: 'cc_raid_rare_helmet_shortage_hud',
        bonusXpMultiplier: 2.5,
    },
    {
        id: 'ra_hemorrhaging',
        name: 'Hemorrhaging',
        positiveEffect: 'Every melee kill regenerates 10% health.',
        negativeEffect: '20% health drained per minute.',
        rarity: 'rare',
        category: 'challenge',
        type: 'raid',
        texture: 'cc_raid_rare_hemorrhaging_hud',
        bonusXpMultiplier: 2.5,
    },
    {
        id: 'ra_crab_people',
        name: 'Crab People',
        positiveEffect: 'Player movement speed is greatly increased.',
        negativeEffect: 'You can only walk backwards or sideways (strafe)',
        rarity: 'rare',
        category: 'challenge',
        type: 'raid',
        texture: 'cc_raid_rare_crab_people_hud',
        bonusXpMultiplier: 3,
    },
    {
        id: 'op_limited_supplies',
        name: 'Limited Supplies',
        positiveEffect: 'Loot pickup rewards increased by 15%',
        negativeEffect: 'Primary and Secondary ammo capacity lowered by 20%',
        rarity: 'common',
        category: 'challenge',
        type: 'operation',
        texture: 'cc_operation_common_limited_supplies_hud',
        bonusXp: 1000,
    },
    {
        id: 'op_take_the_cannoli',
        name: 'Take the Cannoli',
        positiveEffect: 'No movement penalties for carrying heavy objects',
        negativeEffect: 'Enemy loot drop chances lowered by 15%',
        rarity: 'common',
        category: 'challenge',
        type: 'operation',
        texture: 'cc_operation_common_take_the_canonoli_hud',
        bonusXp: 1500,
    },
    {
        id: 'op_everyones_a_tough_guy',
        name: 'Real Tough Guys',
        positiveEffect: 'Bleedout timer increased by 5 seconds.',
        negativeEffect: 'Enemies have 10% more Health',
        rarity: 'common',
        category: 'challenge',
        type: 'operation',
        texture: 'cc_operation_common_everyones_a_tough_guy_hud',
        bonusXp: 1400,
    },
    {
        id: 'op_nichtsplosions',
        name: 'Nichtsplosions',
        positiveEffect: 'Player reload speed increased by 15%',
        negativeEffect: 'Enemies are impervious to explosive damage.',
        rarity: 'common',
        category: 'challenge',
        type: 'operation',
        texture: 'cc_operation_common_nichtsplosions_hud',
        bonusXp: 1200,
    },
    {
        id: 'op_war_weary',
        name: 'War Weary',
        positiveEffect: 'Enemies take 10% more damage',
        negativeEffect: 'Loot pickup rewards reduced by 25%',
        rarity: 'common',
        category: 'challenge',
        type: 'operation',
        texture: 'cc_operation_common_war_weary_hud',
        bonusXp: 800,
    },
    {
        id: 'op_special_for_a_reason',
        name: 'Special Delivery',
        positiveEffect: 'Player movement speed is greatly increased.',
        negativeEffect: 'Special enemies deal 50% more damage.',
        rarity: 'uncommon',
        category: 'challenge',
        type: 'operation',
        texture: 'cc_operation_uncommon_special_for_a_reason_hud',
        bonusXpMultiplier: 1.3,
    },
    {
        id: 'op_dont_blink',
        name: "Don't Blink",
        positiveEffect: 'Loot drop chance increased by 10%',
        negativeEffect: 'Enemy loot drops disappear after 5 seconds.',
        rarity: 'uncommon',
        category: 'challenge',
        type: 'operation',
        texture: 'cc_operation_uncommon_dont_blink_hud',
        bonusXpMultiplier: 1.4,
    },
    {
        id: 'op_bad_coffee',
        name: 'Bad Coffee',
        positiveEffect: 'Player reload speed increased by 10%',
        negativeEffect: 'Bleedout timer reduced to 15 seconds',
        rarity: 'uncommon',
        category: 'challenge',
        type: 'operation',
        texture: 'cc_operation_uncommon_bad_coffee_hud',
        bonusXpMultiplier: 1.6,
    },
    {
        id: 'op_playing_for_keeps',
        name: 'Playing for Keeps',
        positiveEffect: 'Enemies take 10% more damage',
        negativeEffect: 'Player Health is reduced by 25',
        rarity: 'uncommon',
        category: 'challenge',
        type: 'operation',
        texture: 'cc_operation_uncommon_playing_for_keeps_hud',
        bonusXpMultiplier: 1.5,
    },
    {
        id: 'op_silent_shout',
        name: 'Silent Shout',
        positiveEffect: 'Every melee kill regenerates 10% health.',
        negativeEffect: 'Fails if player uses a Warcry.',
        rarity: 'uncommon',
        category: 'challenge',
        type: 'operation',
        texture: 'cc_operation_uncommon_silent_shout_hud',
        bonusXpMultiplier: 1.55,
    },
    {
        id: 'op_blow_me',
        name: 'Blow Me',
        positiveEffect: 'Grenade damage increased by 100%.',
        negativeEffect: 'Primary and Secondary ammo capacity lowered by 50%',
        rarity: 'rare',
        category: 'challenge',
        type: 'operation',
        texture: 'cc_operation_rare_blow_me_hud',
        bonusXpMultiplier: 1.75,
    },
    {
        id: 'op_you_only_live_once',
        name: 'You Only Live Once',
        positiveEffect: 'Health regenerates 5% on every kill.',
        negativeEffect:
            'None of the players can ever die during the duration of the operation.',
        rarity: 'rare',
        category: 'challenge',
        type: 'operation',
        texture: 'cc_operation_rare_you_only_live_once_hud',
        bonusXpMultiplier: 2,
    },
    {
        id: 'op_short_controlled_bursts',
        name: 'Controlled Bursts',
        positiveEffect: 'Critical chances increased by 7%',
        negativeEffect:
            'Must be completed without any player emptying the magazine of any weapon.',
        rarity: 'rare',
        category: 'challenge',
        type: 'operation',
        texture: 'cc_operation_rare_short_controlled_bursts_hud',
        bonusXpMultiplier: 2,
    },
    {
        id: 'op_elite_opponents',
        name: 'Elite Opponents',
        positiveEffect: 'Loot drop chance increased by 25%',
        negativeEffect: 'Enemies have 50% more Health',
        rarity: 'rare',
        category: 'challenge',
        type: 'operation',
        texture: 'cc_operation_rare_elite_opponents_hud',
        bonusXpMultiplier: 2,
    },
    {
        id: 'op_and_headaches_for_all',
        name: 'Headaches For All',
        positiveEffect: 'Headshot damage increased by 50%',
        negativeEffect: 'Enemies vulnerable only to headshots.',
        rarity: 'rare',
        category: 'challenge',
        type: 'operation',
        texture: 'cc_operation_rare_headaches_for_all_hud',
        bonusXpMultiplier: 2.5,
    },
    {
        id: 'ra_b_walk_it_off',
        name: 'Walk it off',
        positiveEffect: 'Bleedout timer increased by 5 seconds.',
        rarity: 'common',
        category: 'booster',
        type: 'raid',
        texture: 'cc_booster_raid_common_walk_it_of_hud',
    },
    {
        id: 'ra_b_in_fine_feather',
        name: 'In fine feather',
        positiveEffect: 'Player Health is increased by 10%',
        rarity: 'uncommon',
        category: 'booster',
        type: 'raid',
        texture: 'cc_booster_raid_uncommon_in_fine_feather_hud',
    },
    {
        id: 'ra_b_precision_fire',
        name: 'Precision fire',
        positiveEffect: 'Enemies take 10% more damage.',
        rarity: 'rare',
        category: 'booster',
        type: 'raid',
        texture: 'cc_booster_raid_rare_precision_shooting_hud',
    },
    {
        id: 'op_b_recycle_for_victory',
        name: 'Recycle for victory',
        positiveEffect: 'Loot pickup rewards increased by 10%',
        rarity: 'common',
        category: 'booster',
        type: 'operation',
        texture: 'cc_booster_operation_common_recycle_for_victory_hud',
    },
    {
        id: 'op_b_will_not_go_quietly',
        name: 'Will not go quietly',
        positiveEffect: 'Bleedout timer increased by 7.5 seconds.',
        rarity: 'uncommon',
        category: 'booster',
        type: 'operation',
        texture: 'cc_booster_operation_uncommon_will_not_go_quietly_hud',
    },
    {
        id: 'op_b_on_top_form',
        name: 'On top form',
        positiveEffect: 'Player Health is increased by 15%',
        rarity: 'rare',
        category: 'booster',
        type: 'operation',
        texture: 'cc_booster_operation_rare_on_top_form_hud',
    },
    {
        id: 'ra_slasher_movie',
        name: 'Slasher movie',
        positiveEffect:
            'Melee damage is increased. Health is regenerated over time.',
        negativeEffect:
            'Player can only use a melee weapon. Warcries are disabled.',
        titleInTexture: true,
        rarity: 'halloween',
        category: 'challenge',
        type: 'raid',
        texture: 'cc_special_raid_slasher_movie_hud',
        bonusXpMultiplier: 2.75,
    },
    {
        id: 'ra_pumpkin_pie',
        name: 'Pumpkin pie',
        positiveEffect: 'Headshot damage increased by 300%',
        negativeEffect: 'Attacking is possible only while in air',
        titleInTexture: true,
        rarity: 'halloween',
        category: 'challenge',
        type: 'raid',
        texture: 'cc_special_raid_pumpkin_pie_hud',
        bonusXpMultiplier: 2.5,
    },
    {
        id: 'ra_season_of_resurrection',
        name: 'Season of resurrection',
        positiveEffect: 'Damage output greatly increased on low HP',
        negativeEffect:
            'There is no bleedout and players can only be revived by others destroying a special pumpkin',
        titleInTexture: true,
        rarity: 'halloween',
        category: 'challenge',
        type: 'raid',
        texture: 'cc_special_raid_season_of_resurrection_hud',
        bonusXpMultiplier: 2.5,
    },
    {
        id: 'ra_holiday_rush',
        name: 'Gift Rush',
        positiveEffect: 'Carry weight penalties are instead positives.',
        negativeEffect:
            'Enemies melee damage to players is increased by 1600%.',
        rarity: 'uncommon',
        category: 'challenge',
        type: 'raid',
        texture: 'cc_debug_card_hud',
    },
    {
        id: 'ra_dooms_day',
        name: 'Doomsday',
        synonyms: ['Dooms Day'],
        positiveEffect: 'Player movement speed is increased by 50%.',
        negativeEffect:
            'Players can only hipfire weapons and can no longer sprint.',
        rarity: 'rare',
        category: 'challenge',
        type: 'raid',
        texture: 'cc_ra_dooms_day_hud',
        bonusXp: 400,
    },
    {
        id: 'free_crowbar',
        name: 'Raise The Bar',
        positiveEffect:
            'All crates are metal lockers and start with a crowbar.',
        rarity: 'common',
        category: 'booster',
        type: 'raid',
        texture: 'cc_free_crowbar_hud',
    },
    {
        id: 'lucky_day',
        name: 'Lucky Day',
        positiveEffect:
            'Critical hit chances and enemy supply drop chances are increased by 10%.',
        rarity: 'rare',
        category: 'booster',
        type: 'raid',
        texture: 'cc_lucky_day_hud',
    },
    {
        id: 'ra_mag_roulette',
        name: 'Mag Roulette',
        positiveEffect: 'Player reload speed increased by 30%',
        negativeEffect:
            'Reloading weapons leaves them with random amount of bullets.',
        rarity: 'rare',
        category: 'challenge',
        type: 'raid',
        texture: 'cc_mag_roulette_hud',
        bonusXp: 350,
    },
    {
        id: 'ra_trick_or_treat',
        name: 'Tricky Treats',
        positiveEffect: 'Killed enemies drop special candy-buff baskets.',
        negativeEffect: 'Most supplies are replaced with candy.',
        rarity: 'halloween',
        category: 'challenge',
        type: 'raid',
        texture: 'cc_trick_or_treat_hud',
        bonusXpMultiplier: 1.75,
    },
    {
        id: 'ra_roulette',
        name: "Feelin' Lucky",
        negativeEffect:
            'When in bleedout the player must win a game of russian roulette.',
        rarity: 'rare',
        category: 'challenge',
        type: 'raid',
        texture: 'cc_debug_card_hud',
        bonusXpMultiplier: 1.5,
    },
    {
        id: 'ra_on_the_scrounge',
        name: 'On the Scrounge',
        positiveEffect: 'Loot pickup rewards increased by 15%',
        negativeEffect: 'Primary and Secondary ammo capacity lowered by 20%',
        rarity: 'common',
        category: 'challenge',
        type: 'raid',
        texture: 'cc_raid_common_on_the_scrounge_hud',
        bonusXp: 400,
    },
    {
        id: 'ra_no_backups',
        name: 'No Backups',
        positiveEffect: 'Player reload speed increased by 15%',
        negativeEffect: 'No secondary weapon. (ammo capacity lowered by 100%)',
        rarity: 'common',
        category: 'challenge',
        type: 'raid',
        texture: 'cc_raid_common_no_backups_hud',
        bonusXp: 350,
    },
    {
        id: 'ra_this_is_gonna_hurt',
        name: 'This is Gonna Hurt',
        positiveEffect: 'Enemies take 15% more damage',
        negativeEffect: 'Bleedout timer reduced to 15 seconds',
        rarity: 'common',
        category: 'challenge',
        type: 'raid',
        texture: 'cc_raid_common_this_is_gonna_hurt_hud',
        bonusXp: 300,
    },
    {
        id: 'ra_not_in_the_face',
        name: 'Not in the Face!',
        positiveEffect: 'Critical chances increased by 10%',
        negativeEffect: "Headshots don't do damage",
        rarity: 'common',
        category: 'challenge',
        type: 'raid',
        texture: 'cc_raid_common_not_in_the_face_hud',
        bonusXp: 450,
    },
    {
        id: 'ra_loaded_for_bear',
        name: 'Loaded for Bear',
        positiveEffect: 'Primary and Secondary ammo capacity increased by 20%',
        negativeEffect: 'All movement speeds reduced by 15%',
        rarity: 'common',
        category: 'challenge',
        type: 'raid',
        texture: 'cc_raid_common_loaded_for_bear_hud',
        bonusXp: 350,
    },
    {
        id: 'ra_total_carnage',
        name: 'Total Carnage!',
        positiveEffect:
            'Ammo pickups refill Equipment. Every enemy is dismembered.',
        negativeEffect: 'Enemies vulnerable only to explosions and melee.',
        rarity: 'uncommon',
        category: 'challenge',
        type: 'raid',
        texture: 'cc_raid_uncommon_total_carnage_hud',
        bonusXpMultiplier: 1.75,
    },
];
