const dictionary: { [key: string]: string } = {
    m24: 'M24 Stielhandgranate',
    betty: 'Spring Mine',
    mills: 'Mills Grenade',
    concrete: 'Concrete Grenade',
    d343: '343d Hand Grenade',
    weapon: 'Weapon butt',
    fists: 'Fists',
    m3_knife: 'M3 Combat Knife',
    robbins_dudley_trench_push_dagger: 'Robbins Dudley Push Dagger',
    german_brass_knuckles: 'German Knuckleduster',
    lockwood_brothers_push_dagger: 'Lockwood Brothers Push Dagger',
    bc41_knuckle_knife: 'BC41 Knuckle Knife',
    km_dagger: "The Admiral's Dagger",
    marching_mace: 'The Marching Mace ',
    lc14b: 'Bloody Machete',
    m1911: 'Colt M1911',
    webley: 'Webley MK VI',
    c96: 'C96 Mauser',
    thompson: 'Thompson M1A1',
    sten: 'Sten MkII',
    garand: 'M1 Garand',
    m1918: 'BAR',
    m1903: 'M1903 Springfield',
    m1912: 'M12',
    mp38: 'MP 38',
    carbine: 'M1 Carbine',
    mp44: 'StG 44',
    mg42: 'MG 42',
    mosin: 'Mosin Nagant',
    sterling: 'Sterling',
    geco: 'Double-Barrel',
    dp28: 'Degtyaryov DP-28',
    tt33: 'Tokarev TT-33',
    ithaca: 'Ithaca 37',
    kar_98k: 'Karabiner 98k',
    bren: 'Bren',
    lee_enfield: 'Lee-Enfield',
    browning: 'Browning Auto-5',
    welrod: 'Welrod',
    shotty: 'Pocket Double-Barrel',
};

export function getWeaponName(weaponId: string) {
    return dictionary[weaponId];
}
